# .goreleaser.yaml
project_name: go-on-jenkins
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
nfpms:
- maintainer: Armando Martinez <armando.martinez.esausi@gmail.com>
  description: Sample project.
  homepage: https://github.com/jarmandomtz/go-on-jenkins
  license: MIT
  formats:
  - deb
  - rpm
